// Evergreen topics the content agent may write about when nothing timely is
// happening. Pure data. Each entry is a working title plus the reader's real
// question, so the researcher knows what the article has to answer.
//
// The agent is told which of these (and which published posts) already exist,
// and must pick something that is not covered yet. Add to this list freely;
// remove entries once a post covers them so the agent stops considering them.
export const TOPIC_BANK = [
  ["How to read every line of a LESCO bill", "What does each box on the bill mean, and which charges can I question?"],
  ["How to read an IESCO bill line by line", "Same as above, for Islamabad and Rawalpindi consumers."],
  ["How to read a MEPCO bill line by line", "Same as above, for Multan region consumers."],
  ["How to read a K-Electric bill", "Karachi consumers: what is different about a KE bill, and what is TV fee, bank charges, etc."],
  ["Time of Use (TOU) meters explained", "What are peak and off-peak hours, who gets a TOU meter, and does it save money?"],
  ["How to apply for a new electricity connection", "Documents, fees, demand notice, timeline, and how to track an application."],
  ["How to change the name on an electricity bill", "Transfer of connection after buying a house or a death in the family."],
  ["How to complain about a wrong meter reading", "Steps, evidence to collect, DISCO helpline, NEPRA complaint route, and timelines."],
  ["Net metering in Pakistan: how it works", "Solar net metering rules, buy-back rate, application process, and what changed recently."],
  ["Electricity theft and detection bills", "What a detection bill is, how it is calculated, and how to contest one."],
  ["How to get a duplicate electricity bill", "Online and office routes for each DISCO, and what to do if the reference number is unknown."],
  ["Late payment surcharge on electricity bills", "How LPS is calculated, when it applies, and whether it can be waived."],
  ["Electricity bill installment plans", "Can a large bill be paid in installments, who approves it, and how to apply."],
  ["Disconnection and reconnection rules", "When a DISCO may cut the supply, notice periods, and reconnection fees."],
  ["How to lower a summer electricity bill in Pakistan", "Practical, measurable steps for AC, fans, fridges, with unit estimates."],
  ["Three-phase vs single-phase connections", "Who needs three-phase, costs, fixed charges, and how to upgrade."],
  ["Prepaid electricity meters in Pakistan", "Where they are being rolled out, how top-ups work, tariff differences."],
  ["Smart meters (AMI) rollout", "Which DISCOs are installing smart meters, what changes for the consumer, and privacy questions."],
  ["Agricultural tubewell electricity tariffs", "Tariff categories, subsidies, and how to read a tubewell bill."],
  ["Commercial electricity tariffs for shops and offices", "A-2 tariff slabs, fixed charges, and how a shop bill is built."],
  ["Industrial electricity tariffs", "B-1 to B-4 categories, MDI charges, and peak-hour costs."],
  ["Lifeline consumers explained", "Who counts as lifeline, the unit thresholds, and the protected rates."],
  ["Quarterly Tariff Adjustment (QTA) explained", "What QTA is, how NEPRA sets it, and how it shows up on the bill."],
  ["Electricity duty and taxes on the bill", "Electricity duty, GST, income tax (advance tax), TV fee: who pays what and why."],
  ["How to check electricity bill by CNIC or mobile", "What is actually possible, what is a myth, and the real lookup routes."],
  ["Bijli bill online check kaise karein (Roman Urdu)", "A plain Roman Urdu walkthrough for first-time users."],
  ["Meter reading date and billing cycle", "Why bills cover odd periods, what the reading date means, and pro-rata slabs."],
  ["Solar panel payback for a Pakistani home", "Realistic payback with current tariffs and net-metering rules, worked example."],
  ["Power outages and load shedding schedules", "How schedules are set, where to find them, and how to report an unscheduled outage."],
  ["Electricity bill for tenants and landlords", "Who is responsible, how to split, and how to get a separate meter."],
  ["How to read your meter yourself", "Digital and analogue meters, how to estimate the coming bill, and spot a faulty meter."],
  ["Capacity payments and why bills are high", "A plain explanation of capacity charges in the generation cost and what consumers can do."],
  ["Mobile apps for electricity bills", "PITC's and the DISCOs' official apps, what they do, and which are fake."],
  ["Paying electricity bills through JazzCash, Easypaisa and banks", "Fees, cut-off times, and how to keep proof of payment."],
  ["Electricity subsidy for low-income consumers", "Current subsidy schemes, eligibility, BISP links, and how to check status."],
  ["Winter electricity package or incremental consumption packages", "Any current incentive scheme for extra consumption, rules and eligibility."],
  ["FESCO bill check and reading guide", "Faisalabad consumers: lookup, reading the bill, helplines."],
  ["GEPCO bill check and reading guide", "Gujranwala consumers: lookup, reading the bill, helplines."],
  ["PESCO bill check and reading guide", "Peshawar consumers: lookup, reading the bill, helplines."],
  ["HESCO, SEPCO and QESCO bills explained", "Sindh and Balochistan consumers: lookup, reading the bill, helplines."],
  ["TESCO bill check and tribal districts", "Lookup and reading for the merged districts of Khyber Pakhtunkhwa."],
  ["Gilgit-Baltistan electricity bill (GB ebilling)", "How GB consumers check and pay their bill, who supplies power there, and how it differs from the DISCOs."],
  ["How to calculate MDI on an electricity bill", "A worked example of maximum demand indicator charges for a three-phase or commercial connection."],
  ["Protected consumer formula with a worked example", "How the six-month 200-unit test is applied month by month, with a real sequence of readings."],
  ["QESCO bill check, including the common misspellings", "Quetta and Balochistan consumers; many search for casco or qasco bill."],
];
